export const TARGET_MUSCLES = [
  "Full Body",
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Biceps",
  "Triceps",
  "Core",
  "Abs",
  "Legs",
  "Quadriceps",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Hip Flexors",
  "Spine",
  "Neck",
] as const;

export const EQUIPMENT_LIST = [
  "None",
  "Dumbbells",
  "Barbell",
  "Resistance Bands",
  "Pull-up Bar",
  "Bench",
  "Kettlebell",
  "Treadmill",
  "Cycling Bike",
  "Jump Rope",
  "Yoga Mat",
  "Foam Roller",
  "Battle Ropes",
  "Box",
  "Medicine Ball",
  "Cable Machine",
  "Smith Machine",
  "TRX Suspension",
] as const;

export const BENEFITS_LIST = [
  "Burns fat effectively",
  "Improves heart health",
  "Boosts metabolism",
  "Increases stamina",
  "Reduces stress",
  "Builds lean muscle",
  "Increases bone density",
  "Improves posture",
  "Enhances flexibility",
  "Improves balance",
  "Boosts energy levels",
  "Improves sleep quality",
  "Reduces anxiety",
  "Increases strength",
  "Improves coordination",
  "Speeds up recovery",
  "Improves range of motion",
  "Reduces injury risk",
] as const;

export type TargetMuscle = (typeof TARGET_MUSCLES)[number];
export type Equipment = (typeof EQUIPMENT_LIST)[number];
export type Benefit = (typeof BENEFITS_LIST)[number];