
export const WORKOUT_EXERCISE_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  SKIPPED: "SKIPPED",
} as const;

export type WorkoutExerciseStatus = (typeof WORKOUT_EXERCISE_STATUS)[keyof typeof WORKOUT_EXERCISE_STATUS];

export interface MarkDayCompletedPayload {
  planId: string;
  dayNumber: number;
  completed: boolean;
}

export interface MarkExerciseStatusPayload {
  planId: string;
  dayNumber: number;
  exerciseId: string;
  status: WorkoutExerciseStatus;
}

export interface WorkoutFormData {
  workoutName: string;
  workoutDescription: string;
  workoutImage: File | null;
  coverPhoto: File | null;
  introVideo: File | null;        
  targetMuscles: string[];
  equipment: string[];
  benefits: string[];
}


export interface Workout {
  id: string;
  workoutName: string;
  workoutDescription: string;
  workoutImage: string;
  coverPhoto: string;
  introVideo: string;
  targetMuscles: string[];
  equipment: string[];
  benefits: string[];
  isActive: boolean;
}


export interface AiWorkoutExercise {
  instanceId: string;
  order: number;
  exerciseId: string;
  exerciseTitle?: string;
  exerciseImage?: string;
  targetMuscles?: string[];
  sets: number;
  reps?: number;
  durationSeconds?: number;
  estimatedDurationSeconds?: number;
  restSeconds: number;
  notes?: string;
  status?: WorkoutExerciseStatus;
  startedAt?: string;
  timeTakenSeconds?: number;
}

export interface GenerateWorkoutDay {
  dayNumber: number;
  day: string;
  type: "workout" | "rest";
  focus: string;
  estimatedDurationMinutes: number;
  status: string;
  completedAt?: string;
  exercises: AiWorkoutExercise[];
}

export interface WorkoutPlan {
  workoutPlanId: string;
  days: GenerateWorkoutDay[];
  planType: 'FREE' | 'PREMIUM';
}

export interface WorkoutPlanResponse extends WorkoutPlan {
  weekNumber: number;
  startDate: string;
  formattedStartDate?: string;
  endDate: string;
  formattedEndDate?: string;
  status: string;
  autoGenerated?: boolean;
}

export interface GetWorkoutPlansResponse {
  plans: WorkoutPlanResponse[];
  generationStatus: {
    canGenerate: boolean;
    isInactive: boolean;
    pendingDaysCount: number;
    hasCompletedWorkoutToday: boolean;
    firstPendingDayNumber: number;
  };
  isPremium?: boolean;
  completedHistory?: CompletedHistoryItem[];
}

export interface CompletedHistoryItem {
  date: string;
  planWeek: number;
  day: GenerateWorkoutDay;
}

export interface WorkoutTrendDataDto {
  label: string;
  completionRate: number;
}

export interface MuscleDistributionDto {
  muscleName: string;
  count: number;
  percentage: number;
}

export interface RecentActivityDto {
  scheduledDate: Date;
  dayName: string;
  status: string;
}

export interface ProgressBarDto {
  title: string;
  goalLabel: string;
  value: number;
  valueLabel: string;
}

export interface PieChartDto {
  labels: string[];
  values: number[];
}

export interface WorkoutProgressResponse {
  currentStreak: number;
  completionRate: number;
  workoutsCompleted: number;
  totalTrainingMinutes: number;

  progressBar: ProgressBarDto;
  pieChart: PieChartDto;

  trendData: WorkoutTrendDataDto[];
  muscleDistribution: MuscleDistributionDto[];
  recentActivities: RecentActivityDto[];
}


